[package]
name = "pacbrew-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
log = "0.4.21"
reqwest = { version = "0.11.25", features = ["stream"] }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
url = "2.5.0"
